# -*- conf -*-
# shell=$SHELL (if set, otherwise user's default shell from /etc/passwd)
# term=foot (or xterm-256color if built with -Dterminfo=disabled)
# login-shell=no

# app-id=foot # globally set wayland app-id. Default values are "foot" and "footclient" for desktop and server mode
# title=foot
# locked-title=no

font=JetBrainsMonoNerdFont-Regular.ttf:size=12
#font-bold=JetBrainsMonoNerdFont-Bold.ttf:size=12
#font-italic=JetBrainsMonoNerdFont-Italic.ttf:size=12
#font-bold-italic=JetBrainsMonoNerdFont-BoldItalic.ttf:size=12
font-size-adjustment=1
vertical-letter-offset=1.2

[colors-dark]
alpha=0.9
blur=true
cursor=232a2e f7a182
background=2d353b
foreground=d3c6aa

regular0=4b565c
regular1=f57f82
regular2=cbe3b3
regular3=f5d098
regular4=b2caed
regular5=f3c0e5
regular6=b3e3ca
regular7=d3c6aa

bright0=4b565c
bright1=f57f82
bright2=cbe3b3
bright3=f5d098
bright4=b2caed
bright5=f3c0e5
bright6=b3e3ca
bright7=d3c6aa

16=f7a182
17=fae6ef

selection-foreground=d3c6aa
selection-background=3d484d

search-box-no-match=232a2e f57f82
search-box-match=d3C6aa 2d353b

jump-labels=232a2e f7a182
urls=b2caed

[colors-light]
alpha=0.9
blur=true
cursor=e8ded5 c69883
background=fdf6e3
foreground=5c6a72

regular0=5c6a72
regular1=c58687
regular2=91a77a
regular3=c4aa80
regular4=8294ad
regular5=c499b8
regular6=719f96
regular7=efebd4

bright0=5c6a72
bright1=c58687
bright2=91a77a
bright3=c4aa80
bright4=8294ad
bright5=c499b8
bright6=719f96
bright7=efebd4

16=c69883
17=c29fb2

selection-foreground=5c6a72
selection-background=F4F0D9

search-box-no-match=EFEBD4 c58687
search-box-match=5c6a72 EFEBD4

jump-labels=EFEBD4 c69883
urls=8294ad
