db_file "/home/liam/.config/mpd/database"
pid_file "/home/liam/.config/mpd/pid"
state_file "/home/liam/.config/mpd/state"

music_directory "/games/Music"
playlist_directory "/games/Music/playlists"

auto_update "yes"
restore_paused "yes"
bind_to_address "localhost"
port "6600"

audio_output {
    type "pipewire"
    name "PipeWire output"
}
