# ~/.config/wallust/themes/everforest-dark.toml
{
    "special": {
	"background": "#2d353b",
	"foreground": "#d3c6aa",
	"cursor"    : "#cbe3b3"
    },
    "colors": {
	"color0" : "#4b565c",
	"color1" : "#f57f82",
	"color2" : "#cbe3b3",
	"color3" : "#f5d098",
	"color4" : "#b2caed",
	"color5" : "#f3c0e5",
	"color6" : "#b3e3ca",
	"color7" : "#d3c6aa",
	"color8" : "#4b565c",
	"color9" : "#f57f82",
	"color10": "#cbe3b3",
	"color11": "#f5d098",
	"color12": "#b2caed",
	"color13": "#f3c0e5",
	"color14": "#b3e3ca",
	"color15": "#d3c6aa"
    }
}
