# -*- conf -*-

# shell=$SHELL (if set, otherwise user's default shell from /etc/passwd)
# term=foot (or xterm-256color if built with -Dterminfo=disabled)
# login-shell=no

# app-id=foot # globally set wayland app-id. Default values are "foot" and "footclient" for desktop and server mode
# title=foot
# locked-title=no

font=JetBrainsMonoNerdFont-Regular.ttf:size=12
#font-bold=JetBrainsMonoNerdFont-Bold.ttf:size=12
#font-italic=JetBrainsMonoNerdFont-Italic.ttf:size=12
#font-bold-italic=JetBrainsMonoNerdFont-BoldItalic.ttf:size=12
font-size-adjustment=1
vertical-letter-offset=1.2

[colors-dark]
alpha=0.9
background=2d353b
foreground=d3c6aa

regular0=4b565c # black
regular1=e67e80 # red
regular2=a7c080 # green
regular3=dbbc7f # yellow
regular4=7fbbb3 # blue
regular5=d699b6 # magenta
regular6=83c092 # cyan
regular7=d3c6aa # white

bright0=4b565c # black
bright1=e67e80 # red
bright2=a7c080 # green
bright3=dbbc7f # yellow
bright4=7fbbb3 # blue
bright5=d699b6 # magenta
bright6=83c092 # cyan
bright7=d3c6aa # white

[colors-light]


